CREATE TABLE EXAM_QUEST_JOIN(
ID INT NOT NULL AUTO_INCREMENT,
EXAM_ID INT,
QUESTION_ID INT,
PRIMARY KEY (ID),
FOREIGN KEY (EXAM_ID) REFERENCES EXAM(ID),
FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
)