CREATE TABLE QUESTION (
ID INT NOT NULL AUTO_INCREMENT,
QUESTION VARCHAR(1000),
QUESTION_TYPE VARCHAR(100),
MARKS DOUBLE,
OPTIONS VARCHAR(3000),
ANSWER VARCHAR(3000),
TIME_ALLOTED DOUBLE,
SUBJECT_ID VARCHAR(300), 
PRIMARY KEY (ID)
)